from __future__ import annotations

from datetime import datetime
from typing import List

from backend.schemas.models import DisclosureAnalysis, GroupedPatentEvidence, KeywordSet, PriorArtComparison


class ReportAgent:
    def run(
        self,
        task_id: str,
        disclosure: DisclosureAnalysis,
        keywords: KeywordSet,
        search_results: List[GroupedPatentEvidence],
        comparisons: List[PriorArtComparison],
    ) -> str:
        selected = [item for item in comparisons if item.add_to_report]
        lines = [
            "# Patent Novelty Search Report",
            "",
            f"Task ID: `{task_id}`",
            f"Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "",
            "## AI Use Notice",
            "This report is generated by an AI-assisted workflow and is not a legal opinion. Manual professional review is required.",
            "",
            "## Invention Summary",
            f"**Title:** {disclosure.title}",
            f"**Technical Field:** {disclosure.technical_field}",
            f"**Problem:** {disclosure.problem}",
            f"**Solution:** {disclosure.solution}",
            "",
            "## Innovation Points",
        ]

        lines.extend([f"- {point}" for point in disclosure.innovation_points] or ["- Not extracted"])
        lines.extend([
            "",
            "## Search Strategy",
            f"**Core terms:** {', '.join(keywords.core_terms)}",
            f"**Expanded terms:** {', '.join(keywords.synonyms)}",
            f"**Classification hints:** {', '.join(keywords.classification_hints)}",
            "",
            "## Retrieved Prior Art",
        ])

        for idx, result in enumerate(search_results, start=1):
            lines.extend([
                f"### {idx}. {result.patent_id} - {result.title}",
                f"- Score: {result.score}",
                f"- Assignee: {result.assignee or 'N/A'}",
                f"- Date: {result.publication_date or 'N/A'}",
                f"- Jurisdiction: {result.jurisdiction or 'N/A'}",
                f"- CPC: {', '.join(result.cpc) or 'N/A'}",
                f"- URL: {result.source_url or 'N/A'}",
                "- Evidence chunks:",
            ])
            for chunk_result in result.evidence_chunks:
                chunk = chunk_result.chunk
                lines.extend([
                    f"  - `{chunk.chunk_id}` | section: `{chunk.section}` | score: {chunk_result.score}",
                    f"    - retrieval: {chunk_result.retrieval_reason}",
                    f"    - matched terms: {', '.join(chunk_result.matched_terms) or 'N/A'}",
                    f"    - evidence: {chunk.text}",
                ])
            lines.extend([
                "",
            ])

        lines.append("## Novelty Risk Analysis")
        for idx, item in enumerate(selected, start=1):
            lines.extend([
                f"### {idx}. {item.patent_id} - {item.title}",
                f"- Relevance score: {item.relevance_score}",
                f"- Risk level: {item.risk_level.value}",
                f"- Recommendation: {item.recommendation}",
                "- Technical overlaps:",
            ])
            lines.extend([f"  - {overlap}" for overlap in item.overlaps] or ["  - N/A"])
            lines.append("- Potential differences:")
            lines.extend([f"  - {diff}" for diff in item.differences] or ["  - N/A"])
            lines.append("- Evidence:")
            lines.extend([f"  - {ev}" for ev in item.evidence] or ["  - N/A"])
            lines.append("")

        if not selected:
            lines.append("No prior art was selected for the report.")

        return "\n".join(lines)
